### ISSUE TITLE
ERROR: Could not install packages due to an OSError: 

### ISSUE THREAD

**Issue by joulethieff** [sakhnevych/CalendarView#10]
An error has occurred. I am unable to install.

(venv) PS C:\venv\helloword> pip install calendar_view
Collecting calendar_view
  Using cached calendar_view-2.1.0-py3-none-any.whl (323 kB)
Requirement already satisfied: Pillow in c:\venv\helloword\venv\lib\site-packages (from calendar_view) (9.2.0)
Installing collected packages: calendar_view
ERROR: Could not install packages due to an OSError: [Errno 22] Invalid argument: 'C:\\venv\\helloword\\venv\\Lib\\site-packages\\calendar_view\\__pycache__\\Icon\r'

(venv) PS C:\venv\helloword> python --version
Python 3.11.0
(venv) PS C:\venv\helloword>

**Comment by sakhnevych** [comment]
Hi @joulethieff , thanks for raising a bug.

It has been fixed in release v2.1.1.
Can you please check that it works as expected?

```bash
pip install calendar-view
```
https://pypi.org/project/calendar-view/

**Comment by joulethieff** [comment]
Thank you.^^
--------------
(venv) PS C:\venv\helloword\helloworld> pip uninstall calendar-view
Found existing installation: calendar-view 2.1.0
Uninstalling calendar-view-2.1.0:
  Downloading calendar_view-2.1.1-py3-none-any.whl (113 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.8/113.8 kB 472.7 kB/s eta 0:00:00
Requirement already satisfied: Pillow in c:\venv\helloword\venv\lib\site-packages (from calendar-view) (9.2.0)
Installing collected packages: calendar-view
Successfully installed calendar-view-2.1.1
